---
services: docker

env:
  # Test package install on all supported OSes.
  - distro: ubuntu1604
    playbook: test.yml
  - distro: ubuntu1404
    playbook: test.yml
  - distro: debian8
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/drAlberT/3749100d13f4143508d56aa5b1ae23ad/raw
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
